- name: Instala IIS no Windows
  hosts: all
  tasks:
  - name: Install IIS feature on {{ inventory_hostname }}
    win_feature:
          name: Web-Server
          state: present
          restart: no
          include_sub_features: yes
          include_management_tools: no

  - name: Move o arquivo index html local para o {{ inventory_hostname }}
    win_copy:
          src: files/index.html
          dest: 'C:\\inetpub\\wwwroot\\index.html'

  - name: Libera a porta de Firewall 80 para o servidor {{ inventory_hostname }}
    win_firewall_rule:
          name: "{{ inventory_hostname }}_80"
          enable: yes
          state: present
          localport: 80
          action: Allow
          direction: In
          protocol: Tcp

  - name: Testa se o IIS esta funcionando da maneira adequada {{ inventory_hostname }}
    win_uri:
          url: "http://{{ inventory_hostname }}"
          return_content: yes
          register: result
          failed_when: "'Yay! Simple Ansible deployed IIS server ...' not in result.content"
